### ISSUE TITLE
error on rebuild script for linux

### ISSUE THREAD

**Issue by Mazuh** [gustavoFreireS/electron-dojo-timer#21]
traceback:

```
> dojo-timer@1.0.0 rebuild /home/mazuh/Programming/electron-dojo-timer
> electron-rebuild

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 5.0.0-21-generic
gyp ERR! command "/usr/bin/node" "/home/mazuh/Programming/electron-dojo-timer/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.10" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/mazuh/Programming/electron-dojo-timer/node_modules/node-pty
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 6

Error: gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 5.0.0-21-generic
gyp ERR! command "/usr/bin/node" "/home/mazuh/Programming/electron-dojo-timer/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.10" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/mazuh/Programming/electron-dojo-timer/node_modules/node-pty
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 6
    at SafeSubscriber._error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/mazuh/Programming/electron-dojo-timer/node_modules/spawn-rx/node_modules/rxjs/internal/Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! dojo-timer@1.0.0 rebuild: `electron-rebuild`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the dojo-timer@1.0.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mazuh/.npm/_logs/2019-09-23T21_35_45_920Z-debug.log
```

os-release data:

```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
```

node version:

```
v10.14.1
```

**Comment by davidcostadev** [comment]
This issue is related on node-preg-gyp https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by davidcostadev** [comment]
@Mazuh please try to run `npm run install` again.
